## 1. Створити список N максимальних (Kmax) або мінімальних(Kmin) елементів колекції.

In [1]:
N = [6, 9, 10, 2, -8, -3, 9, 5, 7, 12, 8, 52]
Kmax = 2
Kmin = 4

N.sort()

maxList = N[-Kmax:]
minList = N[:Kmin]

maxList, minList

([12, 52], [-8, -3, 2, 5])

## 2. Об'єднати багато невеликих рядків в довгий рядок.

In [2]:
rows = ['Сім', 'погод', 'на', 'дворі',':', 'сіє', ',', 'віє', ',','мутить', ',', 'крутить', ',','рве', ',', 'зверху', 'ллє', ',','знизу', 'мете', '.']
result = " ".join(rows)
result

'Сім погод на дворі : сіє , віє , мутить , крутить , рве , зверху ллє , знизу мете .'

## 3. Операції з матрицями:

In [3]:
import numpy as np

M = np.array([[5, -2, 6],[5, 3, 2],[4, 10, -1]])
v = np.array([[4],[3],[5]])

M, v

(array([[ 5, -2,  6],
        [ 5,  3,  2],
        [ 4, 10, -1]]),
 array([[4],
        [3],
        [5]]))

- транспортувати M

In [4]:
Mt = M.transpose()
Mt

array([[ 5,  5,  4],
       [-2,  3, 10],
       [ 6,  2, -1]])

- M*MT=T

In [5]:
T = M * Mt
T

array([[ 25, -10,  24],
       [-10,   9,  20],
       [ 24,  20,   1]])

- інфвертувати T

In [6]:
np.matrix(T).I

matrix([[ 0.01585628, -0.01987104,  0.01687011],
        [-0.01987104,  0.02234478,  0.03000933],
        [ 0.01687011,  0.03000933, -0.00506914]])

- T*v (вектор)

In [7]:
T * v

array([[100, -40,  96],
       [-30,  27,  60],
       [120, 100,   5]])

## 4. До дати (date) додайте d днів та виведіть

In [8]:
import datetime

date = "02/12/2019"
d = 35

dateObj = datetime.datetime.strptime(date, "%d/%m/%Y")
dateRes = dateObj + datetime.timedelta(days=d)
dateRes.strftime("%d/%m/%Y")

'06/01/2020'

## 5. Провести парсинг RSS-каналу

In [9]:
!pip3 install feedparser

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621


In [10]:
import feedparser
feed = feedparser.parse("https://www.liga.net/tech/all/rss.xml")

feed

{'bozo': False,
 'entries': [{'title': 'Украинская компания сделала чат-бот, который поможет запланировать пост в FB после смерти',
   'title_detail': {'type': 'text/plain',
    'language': None,
    'base': 'https://www.liga.net/tech/all/rss.xml',
    'value': 'Украинская компания сделала чат-бот, который поможет запланировать пост в FB после смерти'},
   'links': [{'rel': 'alternate',
     'type': 'text/html',
     'href': 'https://tech.liga.net/technology/novosti/ukrainskaya-kompaniya-sdelala-chat-bot-kotoryy-pomojet-zaplanirovat-post-v-facebook-posle-s'},
    {'length': '14090',
     'type': 'image/jpg',
     'href': 'https://www.liga.net/images/general/2019/08/14/thumbnail-h-20190814101518-5867.jpg',
     'rel': 'enclosure'}],
   'link': 'https://tech.liga.net/technology/novosti/ukrainskaya-kompaniya-sdelala-chat-bot-kotoryy-pomojet-zaplanirovat-post-v-facebook-posle-s',
   'summary': 'Публикация появится после смерти и будет содержать призыв к пожертвованию на благотворительность